language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake
      - gcc-5
      - g++-5

env:
  - TEST_CONFIG=-DFRACKCRYPT_TEST_INTEGRATION=OFF
  - TEST_CONFIG=-DFRACKCRYPT_TEST_UNIT=OFF
script:
  - export CXX=g++-5
  - cmake -DFRACKCRYPT_TEST=ON ${TEST_CONFIG} . && make && ctest -VV
