language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake
      - gcc-5
script:
  - export CXX=g++-5
  - cmake -DFRACKCRYPT_TEST=ON . && make run-tests
