language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake
      - gcc-5
      - g++-5

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

script: ci/script.sh

notifications:
  email: false
