set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/build")

set(CTEST_BUILD_NAME "linux-gcc")
set(CTEST_PROJECT_NAME "frackcrypt")

set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(CTEST_BUILD_OPTIONS "-DFRACKCRYPT_TEST=ON -DFRACKCRYPT_COVERAGE=ON")

set(WITH_COVERAGE TRUE)
set(CTEST_CUSTOM_COVERAGE_EXCLUDE "gtest/*" "test/*")
