add_custom_target(run-tests)
file(WRITE ${CMAKE_BINARY_DIR}/test_sources "")

macro(add_test_sources test_suite)
  foreach(src ${ARGN})
    set(src ${src})
    file(APPEND ${CMAKE_BINARY_DIR}/${test_suite}_test_sources ${CMAKE_CURRENT_LIST_DIR}/${src} "\n")
  endforeach()
endmacro()

macro(get_test_sources test_suite dest_var)
  file(STRINGS ${CMAKE_BINARY_DIR}/${test_suite}_test_sources PATHS)
  foreach(PATH ${PATHS})
    file(RELATIVE_PATH RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${PATH})
    list(APPEND ${dest_var} ${RELATIVE})
  endforeach()
endmacro()
